### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by 3djc** [DAcodedBEAT/GlucoseDirect#19]
I'm trying to compile develop branch, and it fails because it cannot find GitVersion.swift. How is this file supposed to be generated ?

**Comment by DAcodedBEAT** [comment]
<img width="717" alt="image" src="https://github.com/DAcodedBEAT/GlucoseDirect/assets/5031018/27a842d3-cbf7-4ce8-967b-7aaffdbc3387">

It should be generated from the `Run Script` phase, @3djc have you changed anything with the build on your end?

**Comment by 3djc** [comment]
I'll have a look tomorrow, but all I did was clone the repo from Xcode, copy my DiaBLEOverride.xcconfig for my team id, and hit build

**Comment by 3djc** [comment]
Unsure why I don't have it

<img width="1253" alt="Capture d’écran 2023-11-12 à 08 17 56" src="https://github.com/DAcodedBEAT/GlucoseDirect/assets/5167938/4f1eb800-b2e8-426d-a01a-c665f0659433">

**Comment by 3djc** [comment]
Diving into project.pbxproj the section seems there at line 1070, but doesn't show on xcode :s

**Comment by 3djc** [comment]
I'm investigating and it looks like I have in the logs some access right error to .git folder

**Comment by 3djc** [comment]
I have manually run that script and for now it seems ok, but I create a new clone dir, and the issue is the same, so suggesting leaving it open until we understand it better

**Comment by DAcodedBEAT** [comment]
> I'm investigating and it looks like I have in the logs some access right error to .git folder

If there's access error to the .git folder, I suspect it's you might have Xcode configure to sandbox the build, which would prevent the build process to run git commands

**Comment by 3djc** [comment]
Indeed, will change it
